# ./docker-compose.yml
version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: minhasenhapika
      MYSQL_DATABASE: clibrary
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - .:/var/www/
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
