# ./docker-compose.yml
version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: minhasenhapika
      MYSQL_DATABASE: clibrary
    ports:
      - "3306:3306"
    volumes:
      - "./db-data/mysql:/var/lib/mysql"
#  web:
#    image: php:7.4-cli
#    container_name: php_web
#    depends_on:
#      - db
#    volumes:
#      - .:/var/www/
#    secrets:
#      - sshkey_github
#    ports:
#      - "8000:80"
#
#secrets:
#  sshkey_github:
#    file: ~/.ssh/id_rsa
